name: snabbpay
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^4.0.0
  flutter_dropdown: ^0.0.8
  code_fields: ^0.0.2
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # LOGO
    - assets/Login/logo/0.75x/Group 5582.png
    - assets/Login/logo/Group 5582.png
    - assets/Login/logo/1.5x/Group 5582.png
    - assets/Login/logo/2.0x/Group 5582.png
    - assets/Login/logo/3.0x/Group 5582.png 
    - assets/Login/logo/4.0x/Group 5582.png
    #FLAGS
    ## CANADA
    - assets/Login/flags/canada/canada.png
    - assets/Login/flags/canada/0.75x/canada.png
    - assets/Login/flags/canada/1.5x/canada.png
    - assets/Login/flags/canada/2.0x/canada.png
    - assets/Login/flags/canada/3.0x/canada.png
    - assets/Login/flags/canada/4.0x/canada.png
    ## NIGERIA
    - assets/Login/flags/nigeria/nigiria.png
    - assets/Login/flags/nigeria/0.75x/nigiria.png
    - assets/Login/flags/nigeria/1.5x/nigiria.png
    - assets/Login/flags/nigeria/2.0x/nigiria.png
    - assets/Login/flags/nigeria/3.0x/nigiria.png
    - assets/Login/flags/nigeria/4.0x/nigiria.png

    ##ARROW DOWN AND UP
    - assets/Login/arrow_down.png
    - assets/Login/arrow_up.png

    #BACK ARROW 
    - assets/Login/arrow (1)/arrow (1).png
    - assets/Login/arrow (1)/0.75x/arrow (1).png
    - assets/Login/arrow (1)/1.5x/arrow (1).png
    - assets/Login/arrow (1)/2.0x/arrow (1).png
    - assets/Login/arrow (1)/3.0x/arrow (1).png
    - assets/Login/arrow (1)/4.0x/arrow (1).png
    
    #LOCK IMAGE
    - assets/Login/lock/lock.png
    - assets/Login/lock/0.75x/lock.png 
    - assets/Login/lock/1.5x/lock.png
    - assets/Login/lock/2.0x/lock.png
    - assets/Login/lock/3.0x/lock.png
    - assets/Login/lock/4.0x/lock.png
    
    #OTP TICK
    - assets/Login/tick (4)/tick (4).png
    - assets/Login/tick (4)/0.75x/tick (4).png 
    - assets/Login/tick (4)/1.5x/tick (4).png
    - assets/Login/tick (4)/2.0x/tick (4).png 
    - assets/Login/tick (4)/3.0x/tick (4).png 
    - assets/Login/tick (4)/4.0x/tick (4).png 

    #USER ICON
    - assets/Login/user (7)/user (7).png
    - assets/Login/user (7)/0.75x/user (7).png
    - assets/Login/user (7)/1.5x/user (7).png
    - assets/Login/user (7)/2.0x/user (7).png
    - assets/Login/user (7)/3.0x/user (7).png
    - assets/Login/user (7)/4.0x/user (7).png
    
